version: '2.3'
services:
    wass:
        user: ${UID}:${GID}
        restart: "no"
        image: bergamasco/wass:latest
        container_name: wass
        volumes:
            - type: "bind"
            #
            #   Directory containing the configuration files
            #
              source: "./WASS_TEST/W07/config"
              target: "/DATA_CONF"
            - type: "bind"
            #
            #   Directory containing the input images
            #
              source: "./WASS_TEST/W07/input"
              target: "/DATA_IN"
            - type: "bind"
            #
            #  Output directory
            #
              source: "./out"
              target: "/DATA_OUT"
        depends_on:
            - redis
        environment:
            REDISADDR: redis:6379
        ports:
            - 8080:8080
        networks:
            - network1

    redis:
        restart: always
        image: redis
        expose:
            - 6379
        networks:
            - network1

networks:
    network1:
        name: wass-net
